---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/series
  label: series
  create: all
  match: "**/*"
  templates:
  - series-post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/snippet
  label: Snippet
  create: all
  match: "**/*"
- type: directory
  path: content/project
  label: Project
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.88.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
